@endpoint=http://localhost:8080

### 一对多
POST {{endpoint}}/api/cg/generate/code HTTP/1.1
content-type: application/json

{
  "project":"cg",
  "module":"onemary",
  "tableName":"t_classroom",
  "sql":"onemany-schema.sql",
  "slaves":
  [
    {
      "tableName": "t_student",
      "masterId": "classroom_id"
    }
  ]
}


####
POST {{endpoint}}/api/cg/generate/code HTTP/1.1
content-type: application/json
{
  "project":"cg",
  "module":"onemary",
  "tableName":"t_student",
  "sql":"onemany-schema.sql",

}