@endpoint=http://localhost:8080

### 生成带 features 的代码
POST {{endpoint}}/api/cg/generate/code HTTP/1.1
content-type: application/json

{
    "sql": "t_test_saas_entity-schema.sql",
    "project":"t_test_saas_entity",
    "module": "t_test_saas_entity",
    "tableName":"t_test_saas_entity",
    "features":["saas"]
}