@endpoint=http://localhost:8080

@adminToken =Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjowLCJkZXZVc2VyVHlwZSI6MCwiYlVzZXJUeXBlIjoiU1lTVEVNIiwiYlVzZXJJZCI6MCwiaWF0IjoxNjUzMzc5NjY3LCJqdGkiOiIxIiwic3ViIjoiYWRtaW4iLCJleHAiOjE2NTM2Mzg4Njd9.3Wm7Rokrf3ZEVTqWLrYK8V8M5E8zkJRG2YLcEhsJwP68eObzjcJhXaPz2pN_TMS6NQIEdgBFzi7wqfzpxTzYRw

@A_1token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjE4IiwidXNlcklkIjoiNiIsInRlbmFudE9yZ0lkIjoxLCJhY2NvdW50IjoiQS0xIiwidXNlclR5cGUiOjAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJiVXNlcklkIjowLCJpYXQiOjE2NTMzNzI2NzksImp0aSI6IjYiLCJzdWIiOiJBLTEiLCJleHAiOjE2NTM2MzE4Nzl9.blwmLJjVHlEmufX5M7D3K3fHRAEugJfhkJ11EM_OVhIX68rLX2zIEmR8Hg31iWfOmgNURPPdc80focieCyX-Dw

@A_2token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjE5IiwidXNlcklkIjoiNyIsInRlbmFudE9yZ0lkIjoxLCJhY2NvdW50IjoiQS0yIiwidXNlclR5cGUiOjAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJiVXNlcklkIjowLCJpYXQiOjE2NTMzNzQxNDUsImp0aSI6IjciLCJzdWIiOiJBLTIiLCJleHAiOjE2NTM2MzMzNDV9.Evz6efj-F82LBnRAmGLBUtbvBfTodBiVTE8zDhJv5vs0HrqSPQQtN6CJfoEM7zpRF0Ip-Mc6tkz1zXb37Zs5jg

@A_1_1token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjIyIiwidXNlcklkIjoiOCIsInRlbmFudE9yZ0lkIjoxLCJhY2NvdW50IjoiQS0xLTEiLCJ1c2VyVHlwZSI6MCwiZGV2VXNlclR5cGUiOjAsImJVc2VyVHlwZSI6IlNZU1RFTSIsImJVc2VySWQiOjAsImlhdCI6MTY1MzM3MjcyOSwianRpIjoiOCIsInN1YiI6IkEtMS0xIiwiZXhwIjoxNjUzNjMxOTI5fQ.fk1WxkH7cs19ne8UusZa1QY8T73xASXWTlC84ktbAQ8nQmK_VYnXUO6Y5DAfZF-wiQgB3jWoNjPWx878nivfxQ



##租户列表查询
### 超级管理员查看
GET {{endpoint}}/api/crud/tenant/tenantUser/tenantUsers
Authorization:{{adminToken}}

### 用户A-1 用户级别为A-1
GET {{endpoint}}/api/crud/tenant/tenantUser/tenantUsers
Authorization:{{A_1token}}

### A-2
### 用户A-2 用户级别为A-2 和A-1同级别
GET {{endpoint}}/api/crud/tenant/tenantUser/tenantUsers
Authorization:{{A_2token}}

### 用户为A-1-1 用户级别为A-1-1 在A-1级别下
GET {{endpoint}}/api/crud/tenant/tenantUser/tenantUsers
Authorization:{{A_1_1token}}


### 添加租户
POST {{endpoint}}/api/crud/tenant/tenantUser/tenantUsers
Content-Type:application/json
Authorization:{{A_2token}}
{
    "checkIn": "2022-05-24 18:08:39",
    "name": "王五",
    "occupancyDays": 4,
    "roomNumber": "a401",
    "org_id":18
}

### 查看租户
GET {{endpoint}}/api/crud/tenant/tenantUser/tenantUsers/3
Authorization:{{A_2token}}


### 修改租户信息
PUT {{endpoint}}/api/crud/tenant/tenantUser/tenantUsers/3
Authorization:{{A_2token}}
Content-Type:application/json
{
    "checkIn": "2022-05-24 18:08:39",
    "name": "王五",
    "occupancyDays": 4,
    "roomNumber": "a401"
}

### 删除租户
DELETE {{endpoint}}/api/crud/tenant/tenantUser/tenantUsers/4
Authorization:{{A_2token}}