### 一对多含中间表
@endpoint=http://localhost:8080
### 增添学生
POST {{endpoint}}/api/crud/manymany/student/students
Content-Type: application/json
{
    "id":2,
    "name":"鸿",
    "classroom_id":2,
    "address":"黄埔"
}


### 以学生id查询课程
### 2是id
GET {{endpoint}}/api/crud/manymany/student/students/1


###分页查询
GET {{endpoint}}/api/crud/manymany/student/students?pageNum=1&pageSize=2



###以id修改学生信息
### 2是id
PUT {{endpoint}}/api/crud/manymany/student/students/1
Content-Type: application/json
{
    "id":2,
    "name":"鸿",
    "classroom_id":2,
    "address":"黄埔"
}


###以id删除学生
### 2是id
DELETE {{endpoint}}/api/crud/manymany/student/students/2
