SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `t_stu_cour`;

CREATE TABLE `t_stu_cour`(
`id` INT AUTO_INCREMENT,
`stu_id` INT ,
`cour_id` INT,
PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `t_course`;
CREATE TABLE `t_course`(
`id` INT AUTO_INCREMENT NOT NULL,
`name` VARCHAR(150) NOT NULL DEFAULT '',
PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;