SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `t_classroom`;
CREATE TABLE `t_classroom`(
`id` BIGINT AUTO_INCREMENT NOT NULL,
`name` VARCHAR(150) NOT NULL DEFAULT '',
PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `t_student`;
CREATE TABLE t_student (
`id` BIGINT AUTO_INCREMENT,
`name` VARCHAR(30),
`classroom_id` INT,
`address` VARCHAR(100),
PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `t_teacher`;
CREATE TABLE t_teacher (
`id` BIGINT AUTO_INCREMENT,
`name` VARCHAR(30),
`classroom_id` INT,
PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

