version: "3"
# DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
services:
  api:
    image: env-test-saas
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile
    container_name: api
    ports: 
      - 8080:8080

  # 本地构建 standalone.jar 后可执行 
  # docker-compose build local
  # 仅用于构建， 本地构建后，再容器构建例子
  local:
    image: env-test-saas
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile.local
