version: "3"
# DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
services:
  api:
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile
    image: env-test-saas
    container_name: api
    ports: 
      - 8080:8080
    # command: 
    #   - /usr/local/bin/run.sh
    #   - test  # opt [produce, greenfield, test] ## default test