version: "3"
# docker-compose -f docker-compose.yml up --detach --build  ## for recreating th
# COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
services:
  api:
    image: env-test-saas:latest 
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:  # 这个参数说明 mysqlserver 容器将比 api 先启动
      - mysqlserver

  mysqlserver:
    image: zelejs/mysql:5.7
    container_name: mysqlserver
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
  