version: "3"
services:
  api:
    image: env-test-saas
    # COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
    build:
      context: ../.
      dockerfile: ./Docker/Dockerfile
    ports: 
      - 8080:8080

  # 本地构建 standalone.jar 后可执行 
  # docker-compose build local
  # 仅用于构建， 本地构建后，再容器构建例子
  # local:
  #   image: env-test-saas
  #   # COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build local
  #   build:
  #     context: ../
  #     dockerfile: ./Docker/Dockerfile.local
