version: "3"
services:
  api:
    # DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile
    image: env-test-saas
    container_name: api
    ports: 
      - 8080:8080
    command: 
      - /usr/local/bin/run.sh
      - test  # opt [produce, greenfield, test]
